# Generated by Django 4.1.3 on 2022-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('admission_grade', models.FloatField()),
                ('gpa_year_1', models.FloatField()),
                ('thai', models.FloatField()),
                ('math', models.FloatField()),
                ('science', models.FloatField()),
                ('society', models.FloatField()),
                ('hygiene', models.FloatField()),
                ('art', models.FloatField()),
                ('career', models.FloatField()),
                ('english', models.FloatField()),
            ],
        ),
    ]
