# Generated by Django 4.1.3 on 2022-12-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
