# Generated by Django 4.1.3 on 2022-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0002_grades_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='admission_grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='art',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='career',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='english',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gpa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gpa_year_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='hygiene',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='math',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='science',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='society',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='thai',
            field=models.CharField(max_length=50),
        ),
    ]
