# Generated by Django 4.1.3 on 2022-12-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0003_alter_grades_admission_grade_alter_grades_art_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='math',
            new_name='mathematics',
        ),
    ]
