# Generated by Django 4.1.3 on 2022-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0006_alter_grades_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
