# Generated by Django 4.1.4 on 2022-12-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0008_alter_grades_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='major',
        ),
    ]
