# Generated by Django 4.1.4 on 2022-12-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0009_remove_grades_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('admission_grade', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gpa_year_1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('thai', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mathematics', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('science', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('society', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('hygiene', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('art', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('career', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('english', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
