# Generated by Django 4.1.4 on 2023-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0010_gradesinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='ICT', max_length=100)),
                ('admission_grade', models.CharField(default='F', max_length=5)),
                ('gpa_year_1', models.CharField(default='F', max_length=5)),
                ('thai', models.CharField(default='F', max_length=5)),
                ('math', models.CharField(default='F', max_length=5)),
                ('sci', models.CharField(default='F', max_length=5)),
                ('society', models.CharField(default='F', max_length=5)),
                ('hygiene', models.CharField(default='F', max_length=5)),
                ('art', models.CharField(default='F', max_length=5)),
                ('career', models.CharField(default='F', max_length=5)),
                ('english', models.CharField(default='F', max_length=5)),
                ('status', models.CharField(default='Fail', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='ICT', max_length=100)),
                ('admission_grade', models.CharField(default='F', max_length=5)),
                ('gpa_year_1', models.CharField(default='F', max_length=5)),
                ('thai', models.CharField(default='F', max_length=5)),
                ('math', models.CharField(default='F', max_length=5)),
                ('sci', models.CharField(default='F', max_length=5)),
                ('society', models.CharField(default='F', max_length=5)),
                ('hygiene', models.CharField(default='F', max_length=5)),
                ('art', models.CharField(default='F', max_length=5)),
                ('career', models.CharField(default='F', max_length=5)),
                ('english', models.CharField(default='F', max_length=5)),
                ('status', models.CharField(default='Fail', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PureScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='ICT', max_length=100)),
                ('admission_grade', models.CharField(default='F', max_length=5)),
                ('gpa_year_1', models.CharField(default='F', max_length=5)),
                ('thai', models.CharField(default='F', max_length=5)),
                ('math', models.CharField(default='F', max_length=5)),
                ('sci', models.CharField(default='F', max_length=5)),
                ('society', models.CharField(default='F', max_length=5)),
                ('hygiene', models.CharField(default='F', max_length=5)),
                ('art', models.CharField(default='F', max_length=5)),
                ('career', models.CharField(default='F', max_length=5)),
                ('english', models.CharField(default='F', max_length=5)),
                ('status', models.CharField(default='Fail', max_length=50)),
            ],
        ),
    ]
