# Generated by Django 4.1.4 on 2023-01-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo_model', '0011_appliedscience_healthscience_purescience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='GradesInput',
        ),
    ]
